---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bpknpyow/mentari.smkn2-bangkalan.sch.id
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/local/bin/php $DEPLOYPATH/artisan migrate --force
    - /usr/local/bin/php $DEPLOYPATH/artisan optimize:clear
